/** @format */

import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [resultsPage, setResultsPage] = useState(0);
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState([]);

  const handleSearch = async (e) => {
    e.preventDefault();
    const response = await fetch(
      `https://api.semanticscholar.org/graph/v1/paper/search?query=${searchQuery}&fields=title,authors,year,abstract`
    );
    const data = await response.json();

    setSearchResults(data.data);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <div>
          <h1>Search for a paper to start your rabbit hole.</h1>
          <form onSubmit={handleSearch}>
            <input
              type='text'
              value={searchQuery}
              onChange={(e) => {
                setSearchQuery(e.target.value);
              }}
            />
            <br />
            <button type='submit'>Search</button>
          </form>
          {searchResults.map((paper) => (
            <div key={paper.paperId}>
              <h2>{paper.title}</h2>
              <p>{paper.abstract}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}
